spring:
  session:
    store-type: none
  profiles:
    active: dev
  redis:
    database: 0
    host: localhost
    port: 16379
    password: mypass
    timeout: 60000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/grow_all_stage?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    openInView: false
    show_sql: false
    generate-ddl: true
    properties:
      hibernate.jdbc.time_zone: Asia/Kolkata
    hibernate:
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
      ddl-auto: create

